version: "2"
services:
 paper-parser:
   container_name: paper-parser
   image: librairy/paper-parser:latest
   #restart: always
   external_links:
       - column-db
       - document-db
       - graph-db
       - event-bus
   networks:
       - "lnet"
networks:
  lnet:
    external:
      name: distribution_lnet
